### ISSUE TITLE
Cross-origin navigation

### ISSUE THREAD

**Issue by annevk** [w3c/webappsec-upgrade-insecure-requests#12]
https://w3c.github.io/webappsec-upgrade-insecure-requests/#example-navigation suggests cross-origin navigation does not get upgraded. However, https://w3c.github.io/webappsec-upgrade-insecure-requests/#upgrade-request does not have any kind of origin check. How is this achieved?

It seems that Firefox currently does upgrade those (at least if they're part of a redirect chain, I didn't run tests): https://bugzilla.mozilla.org/show_bug.cgi?id=1417901.

**Comment by annevk** [comment]
@mikewest if you could look into this soonish that'd be great.

**Comment by mikewest** [comment]
Skimming the spec (sorry, I haven't read this in a while), I think step 2.4 of https://w3c.github.io/webappsec-upgrade-insecure-requests/#upgrade-request is doing the work for top-level navigation. The [upgrade insecure navigations set](https://w3c.github.io/webappsec-upgrade-insecure-requests/#upgrade-insecure-navigations-set) contains the origins which ought to be upgraded, and is populated in https://w3c.github.io/webappsec-upgrade-insecure-requests/#delivery and https://w3c.github.io/webappsec-upgrade-insecure-requests/#nesting.

If y'all want to change the specced behavior, there's certainly room to discuss it. I think the goal was to allow pages to link to non-secure resources, which seems reasonable to me, but maybe inside a redirect chain is ok?

**Comment by annevk** [comment]
Ah okay, that's how the same-origin check is achieved.

**Comment by annevk** [comment]
I'll close this for now then. I don't think we want a change here, but will reopen if that was wrong.

**Comment by annevk** [comment]
(Appreciate the speedy reply btw!)

**Comment by mikewest** [comment]
(Trying to make up for not being at all good at keeping up with things recently...)
