### ISSUE TITLE
Upgrade frames?

### ISSUE THREAD

**Issue by mikewest** [w3c/webappsec-upgrade-insecure-requests#4]
As written, we don't upgrade cross-origin frame requests (as they are "navigational requests"). We probably should, however.

**Comment by annevk** [comment]
Presumably you want to hook into some other primitive so `window.open()`, `<form>`, `<a>`, etc. are all covered together.

**Comment by mikewest** [comment]
We're hooking into Fetch currently, but only upgrading same-origin navigational requests. I think that's the right behavior (as UIR asserts that a particular page's subresources should be upgraded, but doesn't make that assertion about cross-origin navigations).

The suggestion here is something along the lines of special-casing requests whose target is `document`, but whose target browsing context is a nested browsing context which has the client's browsing context as an ancestor. That is, subresource navigational requests should be upgraded, while non-subresource navigational requests should be upgraded iff they're same-origin.
